# Generated by Django 3.0.8 on 2020-09-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200901_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[(None, '-----'), ('FA', 'Fashion'), ('TY', 'Toys'), ('EL', 'Electronics'), ('HM', 'Home'), ('GA', 'Garden'), ('VH', 'Vehicles'), ('MU', 'Music'), ('AT', 'Art'), ('SP', 'Sports')], default='FA', max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Category'),
        ),
    ]
