# Generated by Django 3.0.8 on 2020-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200903_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('TY', 'Toys'), ('EL', 'Electronics'), ('HM', 'Home'), ('GA', 'Garden'), ('VH', 'Vehicles'), ('MU', 'Music'), ('AT', 'Art'), ('SP', 'Sports')], default='FA', max_length=2, null=True),
        ),
    ]
