# Generated by Django 3.0.8 on 2020-09-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200903_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('number_of_bids', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bidding_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selling_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.Auction_listings')),
            ],
        ),
    ]
