# Generated by Django 3.0.8 on 2020-09-22 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200914_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Watchitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchitem', to='auctions.Auction_listings')),
                ('Watchuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
