# Generated by Django 3.0.8 on 2020-09-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200922_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='number_of_bids',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='Watchuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
