# Generated by Django 3.0.8 on 2020-09-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200927_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='status',
        ),
    ]
