# Generated by Django 3.0.8 on 2020-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201003_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(default='Fashion', max_length=16),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
