# Generated by Django 3.0.8 on 2020-12-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_listings_watching'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
